In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics as st

In [39]:
data= pd.read_csv('Milan.csv') 
data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,346020,Vittoria House,1754612,Franco,NaN,UMBRIA - MOLISE,45.45663,9.22249,Entire home/apt,40,3,0,NaN,NaN,1,198,0,NaN
1,6400,The Studio Milan,13822,Francesca,NaN,TIBALDI,45.44119,9.17813,Private room,100,4,12,2019-04-13,0.08,1,354,0,NaN
2,348448,"Centric studio (Brera). Piano, great view, par...",326090,Lelio,NaN,BRERA,45.47617,9.18873,Entire home/apt,99,1,82,2022-09-11,0.67,1,344,24,NaN
3,18208903,Casa Caterina Parco Nord Milano,125703074,Alessandro,NaN,PARCO NORD,45.52950,9.19361,Entire home/apt,72,3,286,2022-09-12,4.56,2,187,27,NaN
4,364897,Quiet apartment in the docks area,1842096,Claudia,NaN,TICINESE,45.45461,9.17554,Entire home/apt,93,2,43,2019-07-30,0.34,1,77,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19243,46262677,Affitto 1 posto letto in camera condivisa,312676969,Paola,NaN,PARCO DEI NAVIGLI,45.42562,9.11677,Shared room,17,3,6,2022-09-03,1.86,5,257,6,NaN
19244,7016997,The Best Rent - Apartment Fiera Milano,4417813,The Best Rent,NaN,GALLARATESE,45.50999,9.08982,Entire home/apt,149,1,15,2022-06-22,0.17,139,0,5,015146-CIM-00587
19245,41733911,✌ Cozy Flat in Cormano ✌ #iocimettolacasa,329281806,Alice,NaN,BRUZZANO,45.54111,9.17203,Entire home/apt,25,3,30,2021-09-30,0.95,1,57,1,NaN
19246,12866265,Stanza ampia Privata a Bresso vicino Milano,70344145,Erika,NaN,PARCO NORD,45.53982,9.19136,Private room,46,1,8,2022-09-11,2.45,1,31,8,NaN
19247,50589523,Casa da Suite Impera,14743308,Casa Da Suite,NaN,GALLARATESE,45.50953,9.08556,Entire home/apt,214,1,11,2022-06-06,0.80,114,332,10,NaN

In [40]:
#Identificar valores nulos
valores_nulos=data.isnull().sum()
valores_nulos

id                                    0
name                                  9
host_id                               0
host_name                             0
neighbourhood_group               19248
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                        3802
reviews_per_month                  3802
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                           16854
dtype: int64

In [41]:
#Rellenar datos nulos con el valor de media de la columna, y con función forward fill en los datos de texto (fechas)
data["last_review"]=data["last_review"].fillna(method="bfill")
data["reviews_per_month"]=data["reviews_per_month"].fillna(round(data["reviews_per_month"].mean(),3))
data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,346020,Vittoria House,1754612,Franco,NaN,UMBRIA - MOLISE,45.45663,9.22249,Entire home/apt,40,3,0,2019-04-13,1.229,1,198,0,NaN
1,6400,The Studio Milan,13822,Francesca,NaN,TIBALDI,45.44119,9.17813,Private room,100,4,12,2019-04-13,0.080,1,354,0,NaN
2,348448,"Centric studio (Brera). Piano, great view, par...",326090,Lelio,NaN,BRERA,45.47617,9.18873,Entire home/apt,99,1,82,2022-09-11,0.670,1,344,24,NaN
3,18208903,Casa Caterina Parco Nord Milano,125703074,Alessandro,NaN,PARCO NORD,45.52950,9.19361,Entire home/apt,72,3,286,2022-09-12,4.560,2,187,27,NaN
4,364897,Quiet apartment in the docks area,1842096,Claudia,NaN,TICINESE,45.45461,9.17554,Entire home/apt,93,2,43,2019-07-30,0.340,1,77,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19243,46262677,Affitto 1 posto letto in camera condivisa,312676969,Paola,NaN,PARCO DEI NAVIGLI,45.42562,9.11677,Shared room,17,3,6,2022-09-03,1.860,5,257,6,NaN
19244,7016997,The Best Rent - Apartment Fiera Milano,4417813,The Best Rent,NaN,GALLARATESE,45.50999,9.08982,Entire home/apt,149,1,15,2022-06-22,0.170,139,0,5,015146-CIM-00587
19245,41733911,✌ Cozy Flat in Cormano ✌ #iocimettolacasa,329281806,Alice,NaN,BRUZZANO,45.54111,9.17203,Entire home/apt,25,3,30,2021-09-30,0.950,1,57,1,NaN
19246,12866265,Stanza ampia Privata a Bresso vicino Milano,70344145,Erika,NaN,PARCO NORD,45.53982,9.19136,Private room,46,1,8,2022-09-11,2.450,1,31,8,NaN
19247,50589523,Casa da Suite Impera,14743308,Casa Da Suite,NaN,GALLARATESE,45.50953,9.08556,Entire home/apt,214,1,11,2022-06-06,0.800,114,332,10,NaN

In [42]:
#Identificar valores nulos
valores_nulos=data.isnull().sum()
valores_nulos

id                                    0
name                                  9
host_id                               0
host_name                             0
neighbourhood_group               19248
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                           0
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                           16854
dtype: int64

In [43]:
#Eliminamos las clumnas de license y neighborhood group debido a la alta cantidad de outliers, por lo cual consideramos las columnas no muy útiles. 
data=data.dropna(1)

C:\Users\Alberto\AppData\Local\Temp\ipykernel_11876\1814642253.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  data=data.dropna(1)

In [44]:
#Identificar valores nulos
valores_nulos=data.isnull().sum()
valores_nulos

id                                0
host_id                           0
host_name                         0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
dtype: int64

In [45]:
data.to_csv("MilanLimpio")